export const INCLUIR_LOCAL = 'INCLUIR_LOCAL';
export const EXCLUIR_LOCAL = 'EXCLUIR_LOCAL';
export const SELECIONAR_LOCAL = 'SELECIONAR_LOCAL';
export const DESSELECIONAR_LOCAL = 'DESSELECIONAR_LOCAL';
